plugins:
- seejoo.plugins.memo
- seejoo.plugins.chuck
- seejoo.plugins.seen
# - module: seejoo.plugins.test
#   config:
#     foo: bar
#     baz: quux
- module: seejoo.plugins.rss
  config:
    feeds:
    - name: Warsztat Forum
      url: http://forum.warsztat.gd/index.php?type=rss;action=.xml
      frequency: 5 seconds
      announce:
      - cipra